name: "Build and Push Image"

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: Image Tag
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Login Docker"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v4
        with:
          push: 'true'
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-api-actix:${{ github.event.inputs.image-tag }}

      - name: "Run Trivy Vulnerability Scanner"
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: 'docker.io/${{ secrets.DOCKER_USERNAME }}/simple-api-actix:${{ github.event.inputs.image-tag }}'
          format: 'table'
          exit-code: 1
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
